### ISSUE TITLE
Error Uploading file 

### ISSUE THREAD

**Issue by dev-jatin-mehra** [arnab-4/BrainScan-AI#1]
After entering the website using https://brain-scan-ai.vercel.app/ this link, when we try to upload any image or use the sample one it shows error uploading file.
Can you look into it ?

BTW the project is great ..

![Screenshot (302)](https://github.com/user-attachments/assets/27768136-2852-4559-8cd6-c1f7798aa863)

**Comment by arnab-4** [comment]
@dev-jatin-mehra 
If you want to test it, you can run the application locally. Just start both the client and server, and everything should work as expected. The upload failure issue you're seeing is due to the backend server not being ready for production deployment yet—I'll work on fixing that. But for now, running it locally will allow you to proceed.

Let me know if you encounter any issues!
